report.customfields.environment=STG
report.customfields.user=ANDRUX88
report.customfields.host= https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
report.customfields.order=ApplicationVersion,environment,user,host
serenity.browser.maximized=true
webdriver.timeouts.fluentwait=60000
Webdriver.timeouts.implicitlaywait=60000